#!/bin/sh

# TODO le script te balance direct la liste des partitions avec leur mountpoint
# si t'en choisis une déjà montée elle vire (y/N)
# sinon on la monte et on te demande où
# voir la big commande tout en bas

# TODO arrêter d'utiliser sudo !

d=$(lsblk -l -n -o NAME | dmenu)

case $(echo -e "mount\nunmount" | dmenu) in
	"mount") sudo mount --mkdir /dev/$d /mnt/$d && st sudo lf /mnt/$d;;
	"unmount") sudo umount /dev/$d && notify-send Ok || notify-send Pas ok && sudo rmdir /mnt/$d;;
	*) notify-send retard;;
esac

exit

mount $(lsblk -l -n -o NAME,TYPE,MOUNTPOINT | grep part | sed 's/ part//' | dmenu)
