#!/bin/sh

state=$(xinput | grep TouchPad | grep "floating\|slave" -o)

if [ "$state" = "slave" ];
then
	xinput disable $(xinput | grep TouchPad | grep "[0-9][0-9]" -o)
else
	xinput enable $(xinput | grep TouchPad | grep "[0-9][0-9]" -o)
fi
